// BASE :
###
GET http://localhost:3000/



// USER PART :
// GET METHOD(S)
###
GET http://localhost:3000/recipe
###
GET http://localhost:3000/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE
###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE
###
// POST METHOD(S)
POST http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE
Content-Type: application/json

{
  "last_name": "User",
  "first_name": "Name",
  "is_admin": 1,
  "email": "user.name@edu.devinci.fr",
  "password": "user_pass",
  "phone_number": "0606060606"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "user.name@edu.devinci.fr",
  "password": "user_pass"
}
###
// PUT METHOD(S)
PUT http://localhost:3000/user/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE
Content-Type: application/json

{
  "phone_number": "0707070707"
}
###
// DELETE METHOD(S)
DELETE http://localhost:3000/user/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE
###



// RECIPE PART :
// GET METHOD(S)
###
GET http://localhost:3000/recipe
###
GET http://localhost:3000/recipe/1
###
GET http://localhost:3000/recipes

// POST METHOD(S)
###
POST http://localhost:3000/recipe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE
Content-Type: application/json

{
  "name": "Sandwich Jambon-Beurre",
  "difficulty": 1,
  "ingredients": "Baguette ou pain, beurre demi-sel, jambon (avec ou sans couenne).",
  "preparation_time": 5,
  "cooking_time": 0,
  "note": 5
}
###
// PUT METHOD(S)
###
PUT http://localhost:3000/recipe/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE
Content-Type: application/json

{
  "name": "Sandwich jambon-beurre",
  "difficulty": 2,
  "ingredients": "Baguette ou pain, beurre demi-sel ou sans, jambon (avec ou sans couenne)."
}
###
// DELETE METHOD(S)
###
DELETE http://localhost:3000/recipe/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJuYW1lIiwiaXNfYWRtaW4iOjEsImlkIjoxOSwiaWF0IjoxNjczMjAxODMyfQ.XfxIkwiPvKepreIZKbHiogvXt3mi4S2gM5WT26HvkSE